name:                hs-char-mapper
version:             0.1.0.0
github:              "kenho811/hs-char-mapper"
license:             BSD3
author:              "ken.ho"
maintainer:          "kenho811job@gmail.com"
copyright:           "ken.ho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kenho811/hs-char-mapper#readme>

dependencies:
- base >= 4.7 && < 5
- cassava
- containers
- vector
- bytestring
- text

library:
  source-dirs: src

executables:
  hs-char-mapper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-char-mapper

tests:
  hs-char-mapper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-char-mapper
